# ARG VARIANT
# FROM ghcr.io/horserr/base:${VARIANT:-resolute} as base
FROM ghcr.io/horserr/base:latest as base

ENV DEBIAN_FRONTEND=noninteractive

# 避免pip联网检查
ENV PIP_DISABLE_PIP_VERSION_CHECK=1
# 关闭 pip 过时警告
ENV PIP_USE_FEATURE="build-constraint"
# 关闭 root 权限警告
ENV PIP_ROOT_USER_ACTION=ignore

ENV HF_HOME=${HOME}/.cache/huggingface
ENV MODELSCOPE_CACHE=${HOME}/.cache/modelscope
ENV TRANSFORMERS_CACHE=${HOME}/.cache/huggingface/transformers

COPY .devcontainer/scripts/onCreate.sh .devcontainer/scripts/postCreate.sh /usr/local/share/devcontainer/

RUN chmod +x \
  /usr/local/share/devcontainer/onCreate.sh \
  /usr/local/share/devcontainer/postCreate.sh

FROM base as uv

# install uv
# COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
RUN curl -LsSf https://astral.sh/uv/install.sh | sh

ENV UV_LINK_MODE=copy
# 启用字节码编译提高性能
ENV UV_COMPILE_BYTECODE=1
# 使用系统Python，加速构建和依赖安装
ENV UV_NO_MANAGED_PYTHON=1
# 方便 unsloth 安装，自动检测 pytorch 版本。
ENV UV_TORCH_BACKEND=auto
# 默认就往系统环境装，省得每次加 --system
ENV UV_SYSTEM_PYTHON=1
ENV UV_INDEX_STRATEGY="unsafe-best-match"
ENV UV_DEFAULT_INDEX=https://pypi.org/simple/
# ENV UV_INDEX="\
#   https://mirrors.nju.edu.cn/pypi/web/simple/ \
#   https://mirrors.ustc.edu.cn/pypi/simple/ \
#   https://pypi.tuna.tsinghua.edu.cn/simple \
#   https://pypi.nvidia.cn/"

FROM base as pixi

# install pixi
RUN curl -fsSL https://pixi.sh/install.sh | bash
